# Generated by Django 4.2.4 on 2023-09-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_api', '0002_occupation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_rest_api.occupation_details'),
        ),
    ]
